package in.gov.sgp.service;

import in.gov.sgp.dto.Dtos.*; import in.gov.sgp.model.*; import in.gov.sgp.repository.*; import in.gov.sgp.security.JwtService;
import org.springframework.security.core.Authentication; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*; import java.util.stream.*;

@Service @Transactional
public class GovernanceService {
 private final UserRepository users; private final DepartmentRepository departments; private final ComplaintRepository complaints; private final NotificationRepository notifications; private final ContactMessageRepository contacts; private final PasswordEncoder encoder; private final JwtService jwt;
 public GovernanceService(UserRepository u,DepartmentRepository d,ComplaintRepository c,NotificationRepository n,ContactMessageRepository cm,PasswordEncoder e,JwtService j){users=u;departments=d;complaints=c;notifications=n;contacts=cm;encoder=e;jwt=j;}
 public User current(Authentication a){return users.findById(Long.valueOf(a.getName())).orElseThrow(()->new UnauthorizedException("Your account could not be found."));}
 public UserDto currentDto(Authentication a){return userDto(current(a));}
 public UserDto userDto(User u){var d=u.getDepartment();return new UserDto(u.getId(),u.getName(),u.getEmail(),u.getRole(),d==null?null:d.getId(),d==null?null:d.getName(),u.getCreatedAt());}
 public DepartmentDto deptDto(Department d){return new DepartmentDto(d.getId(),d.getName(),d.getDescription(),d.isActive(),d.getCreatedAt());}
 public ComplaintDto complaintDto(Complaint c){var citizen=c.getCitizen();var dep=c.getDepartment();var staff=c.getAssignedStaff();return new ComplaintDto(c.getId(),c.getReference(),c.getTitle(),c.getCategory(),c.getDescription(),c.getLocation(),c.getLatitude(),c.getLongitude(),c.getStatus(),citizen.getId(),citizen.getName(),dep.getId(),dep.getName(),staff==null?null:staff.getId(),staff==null?null:staff.getName(),c.getRemarks(),c.getResolution(),c.getCreatedAt(),c.getUpdatedAt());}
 public AuthResponse register(RegisterRequest x){if(x.role()==Role.ADMIN)throw new IllegalArgumentException("Invalid role.");if(x.role()==Role.STAFF&&x.departmentId()==null)throw new IllegalArgumentException("Staff registration requires a department.");if(users.findByEmailIgnoreCase(x.email().trim()).isPresent())throw new DuplicateException("An account with this email already exists.");var u=new User();u.setName(x.name().trim());u.setEmail(x.email().trim().toLowerCase());u.setPasswordHash(encoder.encode(x.password()));u.setRole(x.role());if(x.departmentId()!=null)u.setDepartment(departments.findById(x.departmentId()).orElseThrow(()->new IllegalArgumentException("Department not found.")));u=users.save(u);return new AuthResponse(jwt.create(u),userDto(u));}
 public AuthResponse login(LoginRequest x){var u=users.findByEmailIgnoreCase(x.email().trim()).orElse(null);if(u==null||!encoder.matches(x.password(),u.getPasswordHash()))throw new UnauthorizedException("The email or password is incorrect.");return new AuthResponse(jwt.create(u),userDto(u));}
 public List<UserDto> listUsers(String search,Role role){Stream<User>s=users.findAllByOrderByCreatedAtDesc().stream();if(search!=null&&!search.isBlank()){String q=search.toLowerCase();s=s.filter(u->u.getName().toLowerCase().contains(q)||u.getEmail().toLowerCase().contains(q));}if(role!=null)s=s.filter(u->u.getRole()==role);return s.map(this::userDto).toList();}
 public List<DepartmentDto> listDepartments(){return departments.findByActiveTrueOrderByNameAsc().stream().map(this::deptDto).toList();}
 public DepartmentDto createDepartment(DepartmentRequest x){if(departments.findByNameIgnoreCase(x.name().trim()).isPresent())throw new DuplicateException("A department with that name already exists.");var d=new Department();d.setName(x.name().trim());d.setDescription(x.description().trim());return deptDto(departments.save(d));}
 public DepartmentDto updateDepartment(long id,DepartmentRequest x){var d=departments.findById(id).orElseThrow(()->new NotFoundException("Department not found."));d.setName(x.name().trim());d.setDescription(x.description().trim());return deptDto(d);}
 public void deleteDepartment(long id){departments.findById(id).ifPresent(d->{d.setActive(false);departments.save(d);});}
 private List<ComplaintDto> filter(List<Complaint> source,String search,ComplaintStatus status,Long dep){Stream<Complaint>s=source.stream();if(search!=null&&!search.isBlank()){String q=search.toLowerCase();s=s.filter(c->c.getReference().toLowerCase().contains(q)||c.getTitle().toLowerCase().contains(q)||c.getCitizen().getName().toLowerCase().contains(q));}if(status!=null)s=s.filter(c->c.getStatus()==status);if(dep!=null)s=s.filter(c->c.getDepartment().getId().equals(dep));return s.sorted(Comparator.comparing(Complaint::getCreatedAt).reversed()).map(this::complaintDto).toList();}
 private Department routeDepartment(ComplaintRequest x){String text=(x.category()+" "+x.title()+" "+x.description()+" "+x.location()).toLowerCase(Locale.ROOT);String name=text.matches(".*(electric|power|street ?light).*")?"Electricity":text.matches(".*(water|leak|tap|supply).*")?"Water Supply":text.matches(".*(waste|garbage|sanit|clean).*")?"Sanitation":text.matches(".*(health|hospital|clinic|medical).*")?"Public Health":text.matches(".*(traffic|transport|signal|bus).*")?"Roads & Transport":text.matches(".*(road|pothole|drain|drainage|storm|flood).*")?"Public Works":null;return (name==null?departments.findById(x.departmentId()):departments.findByNameIgnoreCase(name)).filter(Department::isActive).orElseThrow(()->new IllegalArgumentException("No active department is available for this complaint."));}
 private User autoAssign(Department d){return users.findByRoleAndDepartmentOrderByCreatedAtAsc(Role.STAFF,d).stream().min(Comparator.comparingLong(complaints::countByAssignedStaff)).orElseThrow(()->new IllegalArgumentException("No service staff is available for this department."));}
 public ComplaintDto createComplaint(Authentication a,ComplaintRequest x){var citizen=current(a);var d=routeDepartment(x);var c=new Complaint();c.setReference("SGP-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT));c.setTitle(x.title().trim());c.setCategory(x.category().trim());c.setDescription(x.description().trim());c.setLocation(x.location().trim());c.setLatitude(x.latitude());c.setLongitude(x.longitude());c.setStatus(ComplaintStatus.ASSIGNED);c.setCitizen(citizen);c.setDepartment(d);c.setAssignedStaff(autoAssign(d));c=complaints.save(c);notify(citizen,c,"Complaint "+c.getReference()+" was submitted and assigned to "+c.getAssignedStaff().getName()+".");return complaintDto(c);}
 public List<ComplaintDto> myComplaints(Authentication a,String search,ComplaintStatus status){return filter(complaints.findByCitizenOrderByCreatedAtDesc(current(a)),search,status,null);}
 public List<ComplaintDto> assigned(Authentication a,String search,ComplaintStatus status){var u=current(a);var all=complaints.findAllByOrderByCreatedAtDesc().stream().filter(c->Objects.equals(c.getAssignedStaff(),u)||(c.getAssignedStaff()==null&&c.getDepartment().equals(u.getDepartment())&&c.getStatus()==ComplaintStatus.PENDING)).toList();return filter(all,search,status,null);}
 public List<ComplaintDto> allComplaints(String search,ComplaintStatus status,Long dep){return filter(complaints.findAllByOrderByCreatedAtDesc(),search,status,dep);}
 public ComplaintDto getComplaint(Authentication a,long id){var c=complaints.findById(id).orElseThrow(()->new NotFoundException("Complaint not found."));var u=current(a);if(u.getRole()==Role.CITIZEN&&!c.getCitizen().getId().equals(u.getId())||u.getRole()==Role.STAFF&&(c.getAssignedStaff()==null||!c.getAssignedStaff().getId().equals(u.getId())))throw new NotFoundException("Complaint not found.");return complaintDto(c);}
 private boolean validTransition(ComplaintStatus from,ComplaintStatus to){return from==ComplaintStatus.ASSIGNED&&to==ComplaintStatus.IN_PROGRESS||from==ComplaintStatus.IN_PROGRESS&&(to==ComplaintStatus.RESOLVED||to==ComplaintStatus.REJECTED);}
 public ComplaintDto updateComplaint(Authentication a,long id,ComplaintUpdate x){var u=current(a);var c=complaints.findById(id).orElseThrow(()->new NotFoundException("Complaint not found."));if(u.getRole()==Role.STAFF&&(c.getAssignedStaff()==null||!c.getAssignedStaff().getId().equals(u.getId())))throw new ForbiddenException("You can only update complaints assigned to you.");if(!validTransition(c.getStatus(),x.status()))throw new IllegalArgumentException("Invalid status transition. Complaints must move from ASSIGNED to IN_PROGRESS, then to RESOLVED or REJECTED.");c.setStatus(x.status());if(x.remarks()!=null)c.setRemarks(x.remarks());if(x.resolution()!=null)c.setResolution(x.resolution());c=complaints.save(c);notify(c.getCitizen(),c,"Complaint "+c.getReference()+" status changed to "+c.getStatus().name().replace('_',' ').toLowerCase()+".");return complaintDto(c);}
 private void notify(User u,Complaint c,String message){var n=new Notification();n.setUser(u);n.setComplaint(c);n.setMessage(message);notifications.save(n);}
 public List<NotificationDto> notifications(Authentication a){return notifications.findByUserOrderByCreatedAtDesc(current(a)).stream().map(n->new NotificationDto(n.getId(),n.getMessage(),n.getComplaint()==null?null:n.getComplaint().getId(),n.getComplaint()==null?null:n.getComplaint().getReference(),n.isRead(),n.getCreatedAt())).toList();}
 public void contact(ContactRequest x){var m=new ContactMessage();m.setName(x.name().trim());m.setEmail(x.email().trim());m.setSubject(x.subject().trim());m.setMessage(x.message().trim());contacts.save(m);}
 public CitizenDashboard citizenDashboard(Authentication a){var u=current(a);var list=complaints.findByCitizenOrderByCreatedAtDesc(u);var recent=list.stream().sorted(Comparator.comparing(Complaint::getUpdatedAt).reversed()).limit(4).map(this::complaintDto).toList();return new CitizenDashboard(list.size(),list.stream().filter(c->c.getStatus()==ComplaintStatus.PENDING).count(),list.stream().filter(c->c.getStatus()==ComplaintStatus.IN_PROGRESS).count(),list.stream().filter(c->c.getStatus()==ComplaintStatus.RESOLVED).count(),recent);}
 public StaffDashboard staffDashboard(Authentication a){var u=current(a);var list=complaints.findByAssignedStaffOrderByCreatedAtDesc(u);var overdue=complaints.countByAssignedStaffAndStatusNotInAndCreatedAtBefore(u,List.of(ComplaintStatus.RESOLVED,ComplaintStatus.REJECTED),Instant.now().minus(7,java.time.temporal.ChronoUnit.DAYS));var recent=list.stream().sorted(Comparator.comparing(Complaint::getUpdatedAt).reversed()).limit(4).map(this::complaintDto).toList();return new StaffDashboard(list.size(),list.stream().filter(c->c.getStatus()==ComplaintStatus.IN_PROGRESS).count(),list.stream().filter(c->c.getStatus()==ComplaintStatus.RESOLVED).count(),overdue,recent);}
 public AdminDashboard adminDashboard(){var all=complaints.findAllByOrderByCreatedAtDesc();Map<String,Long> statuses=all.stream().collect(Collectors.groupingBy(c->c.getStatus().name(),LinkedHashMap::new,Collectors.counting()));var db=departments.findAll().stream().map(d->new DepartmentBreakdown(d.getName(),all.stream().filter(c->c.getDepartment().equals(d)).count())).sorted(Comparator.comparingLong(DepartmentBreakdown::count).reversed()).toList();return new AdminDashboard(users.count(),all.size(),all.stream().filter(c->c.getStatus()==ComplaintStatus.RESOLVED).count(),departments.findByActiveTrueOrderByNameAsc().size(),statuses,db,all.stream().limit(5).map(this::complaintDto).toList());}
 public static class DuplicateException extends RuntimeException{public DuplicateException(String m){super(m);}} public static class UnauthorizedException extends RuntimeException{public UnauthorizedException(String m){super(m);}} public static class ForbiddenException extends RuntimeException{public ForbiddenException(String m){super(m);}} public static class NotFoundException extends RuntimeException{public NotFoundException(String m){super(m);}}
}
