package in.gov.sgp.model;
import jakarta.persistence.*; import java.time.Instant;
@Entity @Table(name="complaints")
public class Complaint {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(nullable=false,unique=true,length=30) private String reference;
 @Column(nullable=false,length=180) private String title; @Column(nullable=false,length=80) private String category; @Column(nullable=false,columnDefinition="TEXT") private String description; @Column(nullable=false,length=180) private String location;
 @Column private Double latitude; @Column private Double longitude;
 @Lob @Column(name="photo_data", columnDefinition="LONGTEXT") private String photoData;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=20) private ComplaintStatus status=ComplaintStatus.PENDING;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="citizen_id",nullable=false) private User citizen; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="department_id",nullable=false) private Department department; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="assigned_staff_id") private User assignedStaff;
 @Column(columnDefinition="TEXT") private String remarks; @Column(columnDefinition="TEXT") private String resolution; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
 @PrePersist void pre(){var now=Instant.now();if(createdAt==null)createdAt=now;if(updatedAt==null)updatedAt=now;} @PreUpdate void update(){updatedAt=Instant.now();}
 public Long getId(){return id;} public String getReference(){return reference;} public String getTitle(){return title;} public String getCategory(){return category;} public String getDescription(){return description;} public String getLocation(){return location;} public Double getLatitude(){return latitude;} public Double getLongitude(){return longitude;} public String getPhotoData(){return photoData;} public ComplaintStatus getStatus(){return status;} public User getCitizen(){return citizen;} public Department getDepartment(){return department;} public User getAssignedStaff(){return assignedStaff;} public String getRemarks(){return remarks;} public String getResolution(){return resolution;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;}
 public void setReference(String v){reference=v;} public void setTitle(String v){title=v;} public void setCategory(String v){category=v;} public void setDescription(String v){description=v;} public void setLocation(String v){location=v;} public void setLatitude(Double v){latitude=v;} public void setLongitude(Double v){longitude=v;} public void setPhotoData(String v){photoData=v;} public void setStatus(ComplaintStatus v){status=v;} public void setCitizen(User v){citizen=v;} public void setDepartment(Department v){department=v;} public void setAssignedStaff(User v){assignedStaff=v;} public void setRemarks(String v){remarks=v;} public void setResolution(String v){resolution=v;}
}
