CREATE TABLE departments (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE,
 description TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
CREATE TABLE users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, `role` VARCHAR(20) NOT NULL,
 department_id BIGINT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES departments(id),
 CONSTRAINT chk_user_role CHECK (`role` IN ('CITIZEN','STAFF','ADMIN'))
);
CREATE TABLE complaints (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(30) NOT NULL UNIQUE, title VARCHAR(180) NOT NULL,
 category VARCHAR(80) NOT NULL, description TEXT NOT NULL, location VARCHAR(180) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 citizen_id BIGINT NOT NULL, department_id BIGINT NOT NULL, assigned_staff_id BIGINT NULL,
 remarks TEXT NULL, resolution TEXT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 CONSTRAINT fk_complaint_citizen FOREIGN KEY (citizen_id) REFERENCES users(id),
 CONSTRAINT fk_complaint_department FOREIGN KEY (department_id) REFERENCES departments(id),
 CONSTRAINT fk_complaint_staff FOREIGN KEY (assigned_staff_id) REFERENCES users(id),
 CONSTRAINT chk_complaint_status CHECK (status IN ('PENDING','ASSIGNED','IN_PROGRESS','RESOLVED','REJECTED'))
);
CREATE TABLE notifications (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, message TEXT NOT NULL, user_id BIGINT NOT NULL, complaint_id BIGINT NULL,
 `read` BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id),
 CONSTRAINT fk_notification_complaint FOREIGN KEY (complaint_id) REFERENCES complaints(id)
);
CREATE TABLE contact_messages (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL,
 subject VARCHAR(180) NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
